# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='libary_name',
            new_name='library_name',
        ),
    ]
